"""Add updated_at field to posts and comments table

Revision ID: 924c637d22dd
Revises: 913153526073
Create Date: 2023-04-03 16:25:43.815979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924c637d22dd'
down_revision = '913153526073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
